export default {
  GET_LIST: 'GET_LIST',
  CREATE_TASK: 'CREATE_TASK',
  GET_LIST_ELEMENT: 'GET_LIST_ELEMENT',
  UPDATE_LIST_ELEMENT: 'UPDATE_LIST_ELEMENT',
  DELETE_LIST_ELEMENT: 'DELETE_LIST_ELEMENT',
};
