export default {
  GET_LIST: 'GET_LIST',
  CREATE_LIST_ELEMENT: 'CREATE_LIST_ELEMENT',
  GET_LIST_ELEMENT: 'GET_LIST_ELEMENT',
  UPDATE_LIST_ELEMENT: 'UPDATE_LIST_ELEMENT',
  DELETE_LIST_ELEMENT: 'DELETE_LIST_ELEMENT',
};
