const myMock = [
  { id: 1, name: 'Rick Sanchez', status: 'Alive', species: 'Human' },
  { id: 2, name: 'Morty Smith', status: 'Alive', species: 'Human' },
  { id: 3, name: 'Summer Smith', status: 'Alive', species: 'Human' },
  { id: 4, name: 'Beth Smith', status: 'Alive', species: 'Human' },
  { id: 5, name: 'Jerry Smith', status: 'Alive', species: 'Human' },
  { id: 6, name: 'Abadango Cluster Princess', status: 'Alive', species: 'Alien' },
  { id: 7, name: 'Abradolf Lincler', status: 'unknown', species: 'Human' },
  { id: 8, name: 'Adjudicator Rick', status: 'Dead', species: 'Human' },
  { id: 9, name: 'Agency Director', status: 'Dead', species: 'Human' },
  { id: 10, name: 'Alan Rails', status: 'Dead', species: 'Human' },
  { id: 11, name: 'Albert Einstein', status: 'Dead', species: 'Human' },
  { id: 12, name: 'Alexander', status: 'Dead', species: 'Human' },
  { id: 13, name: 'Alien Googah', status: 'unknown', species: 'Alien' },
  { id: 14, name: 'Alien Morty', status: 'unknown', species: 'Alien' },
  { id: 15, name: 'Alien Rick', status: 'unknown', species: 'Alien' },
  { id: 16, name: 'Amish Cyborg', status: 'Dead', species: 'Alien' },
  { id: 17, name: 'Annie', status: 'Alive', species: 'Human' },
  { id: 18, name: 'Antenna Morty', status: 'Alive', species: 'Human' },
  { id: 19, name: 'Antenna Rick', status: 'unknown', species: 'Human' },
  { id: 20, name: 'Ants in my Eyes Johnson', status: 'unknown', species: 'Human' }
]
